export const enhancedItineraries = [
    {
        id: 1,
        day: "Day 1",
        title: "Arrival in Colombo",
        description:
            "Welcome to Sri Lanka! Begin your journey with a comprehensive city tour of Colombo, exploring its vibrant streets, colonial architecture, and modern landmarks.",
        image: "/src/assets/img/card-Colombo.jpg",
        duration: "full-day",
        difficulty: "Easy" as const,
        category: "culture",
        price: "$75",
        highlights: ["Gangaramaya Temple", "Independence Square", "Pettah Market", "Galle Face Green", "National Museum"],
        included: ["Professional guide", "Transportation", "Entrance fees", "Welcome lunch", "Hotel pickup/drop-off"],
    },
    {
        id: 2,
        day: "Day 2",
        title: "Sigiriya Rock Fortress",
        description:
            "Climb the iconic Sigiriya Rock Fortress and immerse yourself in its ancient history, stunning frescoes, and breathtaking panoramic views from the summit.",
        image: "/src/assets/img/card-Sigiriya.jpg",
        duration: "full-day",
        difficulty: "Moderate" as const,
        category: "culture",
        price: "$95",
        highlights: ["Ancient Rock Fortress", "Mirror Wall", "Lion's Gate", "Royal Gardens", "Sigiriya Frescoes"],
        included: ["Expert guide", "Entrance tickets", "Transportation", "Lunch", "Water bottles", "First aid kit"],
    },
    {
        id: 3,
        day: "Day 3",
        title: "Cultural Kandy Experience",
        description:
            "Discover the cultural capital of Sri Lanka, including visits to the sacred Temple of the Tooth Relic, Royal Botanical Gardens, and traditional cultural performances.",
        image: "/src/assets/img/card-Kandy.jpg",
        duration: "full-day",
        difficulty: "Easy" as const,
        category: "culture",
        price: "$85",
        highlights: ["Temple of the Tooth", "Royal Botanical Gardens", "Kandy Lake", "Cultural Dance Show", "Gem Museum"],
        included: ["Cultural guide", "All entrance fees", "Traditional lunch", "Cultural show tickets", "Transportation"],
    },
    {
        id: 4,
        day: "Day 4",
        title: "Tea Plantations in Nuwara Eliya",
        description:
            "Visit the lush tea plantations of Nuwara Eliya, learn about tea processing, enjoy scenic train rides, and experience the cool climate of 'Little England'.",
        image: "/src/assets/img/card-NuwaraEliya.jpg",
        duration: "full-day",
        difficulty: "Easy" as const,
        category: "nature",
        price: "$90",
        highlights: ["Tea Factory Tour", "Gregory Lake", "Strawberry Fields", "Victoria Park", "Train Journey"],
        included: ["Tea plantation tour", "Tea tasting session", "Train tickets", "Lunch", "Professional guide"],
    },
    {
        id: 5,
        day: "Day 5",
        title: "Yala Wildlife Safari",
        description:
            "Experience a thrilling safari at Yala National Park, home to leopards, elephants, and diverse wildlife. Early morning and evening game drives for optimal wildlife viewing.",
        image: "/src/assets/img/card-Yala.jpg",
        duration: "full-day",
        difficulty: "Easy" as const,
        category: "wildlife",
        price: "$120",
        highlights: ["Leopard Spotting", "Elephant Herds", "Bird Watching", "Crocodiles", "Sloth Bears"],
        included: ["4WD safari vehicle", "Professional tracker", "Park entrance", "Breakfast", "Lunch", "Binoculars"],
    },
    {
        id: 6,
        day: "Day 6",
        title: "Ella Hill Country Adventure",
        description:
            "Explore the scenic hill country of Ella with visits to Nine Arch Bridge, Little Adam's Peak hike, and breathtaking viewpoints over tea-covered mountains.",
        image: "/src/assets/img/card-Ella.jpg",
        duration: "full-day",
        difficulty: "Moderate" as const,
        category: "adventure",
        price: "$80",
        highlights: ["Nine Arch Bridge", "Little Adam's Peak", "Ella Rock", "Tea Plantations", "Ravana Falls"],
        included: ["Hiking guide", "Transportation", "Lunch", "Water", "Safety equipment", "Photography assistance"],
    },
    {
        id: 7,
        day: "Day 7",
        title: "Galle Fort & Southern Beaches",
        description:
            "Explore the historic Galle Fort with its Dutch colonial architecture, lighthouse, and ramparts, followed by relaxation on pristine southern beaches.",
        image: "/src/assets/img/card-Galle.jpg",
        duration: "full-day",
        difficulty: "Easy" as const,
        category: "culture",
        price: "$70",
        highlights: ["Galle Fort", "Dutch Reformed Church", "Lighthouse", "Unawatuna Beach", "Stilt Fishermen"],
        included: ["Historical guide", "Fort entrance", "Beach time", "Seafood lunch", "Transportation"],
    },
    {
        id: 8,
        day: "Day 8",
        title: "Horton Plains World's End",
        description:
            "Embark on an adventurous hike through Horton Plains National Park to World's End cliff, Baker's Falls, and experience unique montane ecosystem.",
        image: "/src/assets/img/card-HortonPlains.jpg",
        duration: "full-day",
        difficulty: "Challenging" as const,
        category: "adventure",
        price: "$100",
        highlights: ["World's End Cliff", "Baker's Falls", "Endemic Flora", "Cloud Forest", "Sunrise Views"],
        included: ["Early morning pickup", "Park fees", "Hiking guide", "Breakfast", "Packed lunch", "Rain gear"],
    },
]
